import os

# --- Configuration ---
# Path to the directory containing your Lua bot config files,
# relative to where this Python script is run.
CONFIG_DIR_RELATIVE_PATH = "scripts/configs"

# Path where the generated Lua file should be saved,
# relative to where this Python script is run.
GENERATED_LUA_FILE_PATH = "scripts/auto_generated_bot_configs.lua"

# The Lua module prefix needed to require files from your CONFIG_DIR_RELATIVE_PATH.
# Example: if configs are in "scripts/configs/" and "scripts" is a Lua root,
# then "scripts.configs." is the prefix.
LUA_MODULE_PREFIX = "scripts.configs."
# --- End Configuration ---

def find_lua_config_files(config_dir):
    """Scans the config directory for .lua files."""
    lua_files = []
    if not os.path.isdir(config_dir):
        print(f"Error: Config directory not found: {config_dir}")
        return lua_files

    for filename in os.listdir(config_dir):
        if filename.endswith(".lua") and filename != os.path.basename(GENERATED_LUA_FILE_PATH): # Avoid including the generated file itself
            # Remove the .lua extension to get the module name part
            module_name_part = filename[:-4]
            lua_files.append(module_name_part)
    return lua_files

def generate_lua_file_content(module_names, lua_module_prefix):
    """Generates the content for the Lua file."""
    content = "-- This file is automatically generated by generate_lua_config_list.py\n"
    content += "-- Do not edit manually!\n\n"
    content += "return {\n"

    for name in module_names:
        full_module_path = lua_module_prefix + name
        content += f'    "{full_module_path}",\n'

    content += "}\n"
    return content

def main():
    # Get the absolute path to the config directory
    script_dir = os.path.dirname(os.path.abspath(__file__)) # Directory of the python script
    config_dir_abs = os.path.join(script_dir, CONFIG_DIR_RELATIVE_PATH)
    generated_lua_file_abs = os.path.join(script_dir, GENERATED_LUA_FILE_PATH)

    print(f"Scanning for Lua config files in: {config_dir_abs}")
    module_names = find_lua_config_files(config_dir_abs)

    if not module_names:
        print("No .lua config files found (or config directory is empty/missing).")
        # Optionally, still generate an empty Lua table
        # lua_content = "return {}\n"
    # else:
    print(f"Found config modules: {module_names}")

    lua_content = generate_lua_file_content(module_names, LUA_MODULE_PREFIX)

    try:
        # Ensure the directory for the generated file exists
        os.makedirs(os.path.dirname(generated_lua_file_abs), exist_ok=True)
        
        with open(generated_lua_file_abs, "w") as f:
            f.write(lua_content)
        print(f"Successfully generated Lua config list at: {generated_lua_file_abs}")
    except IOError as e:
        print(f"Error writing generated Lua file: {e}")

if __name__ == "__main__":
    main()
