-- server_init.lua (Using Auto-Generated Config List)

-- Load the BotBase system ONCE.
local BotBase = require("scripts/bot_base")
if not BotBase then
    print("SERVER ERROR: Failed to load BotBase system. Bots will not function.")
    return
end

print("SERVER_INIT: Attempting to load bot configurations from auto-generated list...")

-- Path to the Lua file generated by the Python script
local AUTO_GENERATED_CONFIG_LOADER_PATH = "scripts.auto_generated_bot_configs"

local manifest_load_status, config_module_paths = pcall(require, AUTO_GENERATED_CONFIG_LOADER_PATH)

if manifest_load_status and type(config_module_paths) == "table" then
    if #config_module_paths == 0 then
        print("SERVER_INIT: No bot configurations listed in the auto-generated file.")
    else
        print("SERVER_INIT: Found " .. #config_module_paths .. " bot configurations to load.")
    end

    for i, module_path_for_require in ipairs(config_module_paths) do
        print("SERVER_INIT: Attempting to load and create bot from config: " .. module_path_for_require)
        local load_status, config_data_or_error = pcall(require, module_path_for_require)
        
        if load_status then
            if type(config_data_or_error) == "table" then
                local bot_instance_status, bot_instance_or_err = pcall(BotBase.new, config_data_or_error)
                if not bot_instance_status then
                     print("SERVER WARNING: Error creating bot instance from " .. module_path_for_require .. ". Error: " .. tostring(bot_instance_or_err))
                end
            else
                print("SERVER WARNING: Config " .. module_path_for_require .. " loaded but did not return a table.")
            end
        else
            print("SERVER WARNING: Failed to load config " .. module_path_for_require .. ". Error: " .. tostring(config_data_or_error))
        end
    end
else
    print("SERVER WARNING: Could not load or parse auto-generated config loader '" .. AUTO_GENERATED_CONFIG_LOADER_PATH .. "'. Error: " .. tostring(config_module_paths))
    print("SERVER_INIT: Ensure you have run the Python script (e.g., generate_lua_config_list.py) to create this file.")
end

print("SERVER_INIT: Bot configuration loading process completed.")
